### ISSUE TITLE
key not found: "API_HOST" (KeyError)

### ISSUE THREAD

**Issue by antecode** [FarmBot/Farmbot-Web-App#1462] opened 2019-09-26 08:31 UTC
# Expected Behavior
run successful on local host after editing the .env file

# Actual Behavior
![issue3](https://user-images.githubusercontent.com/37802759/65672126-32c11c00-e051-11e9-9b57-5e72cc496726.PNG)

**Comment by antecode** [comment] 2019-09-26 08:34
Hi, I would appreciate any help on this. am installing farmbot webapp on localhost ubuntu 18. I have followed this guide 
https://github.com/FarmBot/Farmbot-Web-App/blob/master/ubuntu_example.sh
 every step but getting to this.
Best regards
Antony.

**Comment by AscendFB** [comment] 2019-09-26 10:24
What did you write into the[ `API_HOST` parameter](https://github.com/FarmBot/Farmbot-Web-App/blob/master/example.env#L24)  in your .env file? 
At which command from the guide did this error come up? I assume when you tried to start the server (`sudo docker-compose up`), right?

**Comment by RickCarlino** [comment] 2019-09-26 12:44
@antecode This could be caused by a number of things. The error is indicative that the .env file is either missing or not being used because of local configuration.

 * Did you run the server using `docker-compose`? The `.env` file will not work if you run the app locally without `docker-compose`. Although it is possible to run the app without `docker-compose`, it _requires modification to the application_ and it is not a use case that FarmBot provides support for. 
 * The `.env` file needs to be at the root of the project. Try running `ls .env` from the project root to make sure it is there.
 * Did you accidentally put your .env files into `example.env` rather than a new `.env`?

Please let me know if that helps.

**Comment by antecode** [comment] 2019-09-27 08:32
Hi, thank you for quick response
 @AscendFB this is the API_HOST in my .env file  API_HOST=127.0.0.1. the error only appears when I start server `rails server`

@RickCarlino yes I did run `docker-compose`, the .env file is in root directory of the project. I checked this but still same error is persisting maybe there is somewhere am not getting right.

**Comment by AscendFB** [comment] 2019-09-27 09:16
@antecode API_HOST=127.0.0.1 should not be used and causes a different error on my setup. Try a real accessible IP address.
Can`t see what went wrong there. Any hints to your API_HOST setting or similar in that flood of logs?

**Comment by antecode** [comment] 2019-09-27 09:19
@AscendFB let me see. thank you

**Comment by AscendFB** [comment] 2019-09-27 09:23
A completely missing `.env` file throws this error to me, so I believe something in your .env config file is not how its supposed to be:

![image](https://user-images.githubusercontent.com/23129562/65758258-15578500-e119-11e9-9433-5485c88b8db1.png)

But no matter what I typed or tried, I've never managed to get the same output as you. Lets hope that Rick knows whats up ...

**Comment by antecode** [comment] 2019-09-27 09:31
yes I believe it is something to do with my .env that's what am trying to understand. also in my case a totally missing .env gives me same as yours 
![issue](https://user-images.githubusercontent.com/37802759/65759039-c6165200-e122-11e9-88e1-cbe3d26dec6b.PNG)

**Comment by RickCarlino** [comment] 2019-09-27 13:20
@antecode I just spun up an Ubuntu 18 virtual machine on Digital Ocean and had no issues getting the server to run using only the instructions provided in [ubuntu_example.sh](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/ubuntu_example.sh).

I am closing this issue because FarmBot, Inc. does not provide setup help for self-hosted servers and the setup instructions appear to work on a fresh Ubuntu installation at the time of writing.

Please feel free to continue the discussion in this thread with community members.

**Closed by RickCarlino** 2019-09-27 13:20 UTC

**Comment by AscendFB** [comment] 2019-09-27 14:27
@antecode I'm still with you as far as I can help. I'd recommend to go for a completely new build and make sure that you don't miss a thing from the ubuntu_example.sh file. I also did a rebuild last week on oracle's VirtualBox, and it worked fine.

**Comment by antecode** [comment] 2019-09-29 09:18
thank you @RickCarlino. I will redo it all again following all step keenly. I am gonna get it right this time
@AscendFB thanks much.  am going to a completely new build and will post back results. am so hopeful and positive it is going to work this time round

**Comment by hankeet** [comment] 2020-02-01 13:50
> 谢谢@RickCarlino。敏锐地完成所有步骤后，我将重新做一遍。这次我会正确的
> @AscendFB非常感谢。将要建立一个全新的版本，并将发布结果。充满希望和积极，这次将继续运作

Hi,bro,did you solve the problem？
